### PR TITLE
Fix/inspect pypi

### PR DESCRIPTION
**Pull request by dsludwig**
The extra `*args, **kwargs` was added to the wrong function.

I also added a unit-test verifying that a sdist package could be uploaded. I duplicated the test data from the `binstar_client/inspect_package/tests/data`. I wonder if there is a clean way to reference this test data? Or if all the test data should live under `binstar_client/tests/data`? There are a few different ways these references are being built right now.

### CODE REVIEW

**Comment by dsludwig** [comment]
@srossross any thoughts on organizing the test data?

**Comment by srossross** [comment]
Fixes #230

**Comment by srossross** [comment]
> @srossross any thoughts on organizing the test data?

No, what did you have in mind?

**Comment by dsludwig** [comment]
After consideration, I don't much mind how it is right now. My concern was that having a test file with the same name in two different test data directories would be slightly confusing. If someone wanted to add or modify test files in the same directory, they'd need to figure out which directory to look at. But the data directories are close enough to the tests that it shouldn't be hard.

Right now there are 7 `data_dir`/`data_path` method definitions:

* CLITestCase defines `data_dir` method, locates all test files in `binstar_client/tests/data`
* `binstar_client/inspect_package/tests/*.py` each define a `data_path` function, relative to `__file__`
* `binstar_client/utils/notebook/tests/*.py` each define a `data_dir` method, relative to `__file__`

It might be nice to clean this up, but there's not much reason to block this PR on that nit.

**Comment by dsludwig** [comment]
@malev can you review?

**Comment by srossross** [comment]
> It might be nice to clean this up, but there's not much reason to block this PR on that nit.

Great idea tho, can you create a new issue for this? I think it should go into our backlog.

**Comment by dsludwig** [comment]
> Great idea tho, can you create a new issue for this? I think it should go into our backlog.

See #242

**Comment by srossross** [comment]
:+1:

**Pull request merged**
