### PR TITLE
Use basename to detect platform and package name

### PR DESCRIPTION
**Pull request by dsludwig**
Instead of using the entire file path.

If you upload an egg with the path `/tmp/has-dash/test_package34-0.3.1-py2.7.egg`, it will have a detected python_version of `0.3.1` and platform of `py2.7`, since it is counting dashes in the entire file path, instead of just the filename.

### CODE REVIEW

**Comment by srossross** [comment]
@dsludwig do you mind adding a test to ensure this stays fixed?

**Comment by dsludwig** [comment]
screen shot 2015-11-12 at 1 23 32 pm

**Comment by dsludwig** [comment]
I added a test for this - it's a bit convoluted, creating and deleting temporary directories/files. If you have any ideas on how to simplify this, they would be appreciated.

**Comment by dsludwig** [comment]
Ok, I made the checks more specific - just the attributes that are expected to differ.

**Comment by srossross** [comment]
:+1:

**Pull request merged**
