### PR TITLE
Fix package upload using PyOpenSSL

### LINKED ISSUE #222: `anaconda upload` fails to upload package from Win64
While trying to upload a package with `anaconda upload` an error occurs: 

	D:\Anaconda\conda-bld\win-64>anaconda upload cchardet-1.0.0-py27_0.tar.bz2
	Using anaconda-server api site https://api.anaconda.org
	detecting package type ...
	conda
	extracting package attributes for upload ...
	done

	Uploading file User/cchardet/1.0.0/win-64/cchardet-1.0.0-py27_0.tar.bz2 ...
	 uploaded 0 of 80Kb: 0.00% ETA: 0.0 minutes[TypeError] cannot make memory view because object does not have the buffer interface
	Traceback (most recent call last):
	  File "D:\Anaconda\Scripts\anaconda-script.py", line 5, in <module>
		sys.exit(main())
	  File "D:\Anaconda\lib\site-packages\binstar_client\scripts\cli.py", line 93, in main
		description=__doc__, version=version)
	  File "D:\Anaconda\lib\site-packages\binstar_client\scripts\cli.py", line 75, in binstar_main
		return args.main(args)
	  File "D:\Anaconda\lib\site-packages\binstar_client\commands\upload.py", line 203, in main
		callback=upload_print_callback(args))
	  File "D:\Anaconda\lib\site-packages\binstar_client\__init__.py", line 425, in upload
		s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, timeout=10 * 60 * 60, headers=headers)
	  File "D:\Anaconda\lib\site-packages\requests\api.py", line 109, in post
		return request('post', url, data=data, json=json, **kwargs)
	  File "D:\Anaconda\lib\site-packages\requests\api.py", line 50, in request
		response = session.request(method=method, url=url, **kwargs)
	  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 468, in request
		resp = self.send(prep, **send_kwargs)
	  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 576, in send
		r = adapter.send(request, **kwargs)
	  File "D:\Anaconda\lib\site-packages\requests\adapters.py", line 370, in send
		timeout=timeout
	  File "D:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 559, in urlopen
		body=body, headers=headers)
	  File "D:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 353, in _make_request
		conn.request(method, url, **httplib_request_kw)
	  File "D:\Anaconda\lib\httplib.py", line 1053, in request
		self._send_request(method, url, body, headers)
	  File "D:\Anaconda\lib\httplib.py", line 1093, in _send_request
		self.endheaders(body)
	  File "D:\Anaconda\lib\httplib.py", line 1049, in endheaders
		self._send_output(message_body)
	  File "D:\Anaconda\lib\httplib.py", line 897, in _send_output
		self.send(message_body)
	  File "D:\Anaconda\lib\httplib.py", line 866, in send
		self.sock.sendall(datablock)
	  File "D:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 216, in sendall
		data = memoryview(data)
	TypeError: cannot make memory view because object does not have the buffer interface

Current conda install:

				 platform : win-64
			conda version : 3.18.3
	  conda-build version : 1.18.1
		   python version : 2.7.10.final.0
		 requests version : 2.8.1
		 root environment : D:\Anaconda  (writable)
	  default environment : D:\Anaconda
		 envs directories : D:\Anaconda\envs
			package cache : D:\Anaconda\pkgs
			 channel URLs : https://repo.continuum.io/pkgs/free/win-64/
							https://repo.continuum.io/pkgs/free/noarch/
							https://repo.continuum.io/pkgs/pro/win-64/
							https://repo.continuum.io/pkgs/pro/noarch/
							https://conda.anaconda.org/User/win-64/
							https://conda.anaconda.org/User/noarch/
			  config file : C:\Users\User\.condarc
		is foreign system : False

### PR DESCRIPTION
**Pull request by dsludwig**
Request body must only use bytes, rather than unicode objects.

Using `six.b` together with `unicode_literals` does not work correctly -
on Python 2.7, `six.b` is a pass-through (i.e. `lambda x: x`). If we are
using `unicode_literals`, then we should explicitly encode or use
`b'strings'` where appropriate.

Fixes #222, anaconda-server/anaconda-build#108

### CODE REVIEW

**Comment by rafaelhbarros** [comment]
This won't work because of this traceback:

Using anaconda-server api site https://api.anaconda.org
Getting build product: /Users/rdebarros/work/anaconda-server
Submitting 1 sub builds
 0) linux-64    python=2.7       None           
Archiving build directory for upload ...
Created archive (805 files); Uploading to binstar
 uploaded 122 of 6108Kb: 2.00% ETA: 0.6 minutes[ERROR] 
Traceback (most recent call last):
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/bin/anaconda", line 9, in <module>
    load_entry_point('anaconda-client==1.1.2+14.g241ef3c', 'console_scripts', 'anaconda')()
  File "/Users/rdebarros/work/anaconda_client/binstar_client/scripts/cli.py", line 82, in main
    description=__doc__, version=version)
  File "/Users/rdebarros/work/anaconda_client/binstar_client/scripts/cli.py", line 64, in binstar_main
    return args.main(args)
  File "/Users/rdebarros/work/anaconda-build/binstar_build_client/build_commands/submit.py", line 207, in main
    submit_build(binstar, args)
  File "/Users/rdebarros/work/anaconda-build/binstar_build_client/build_commands/submit.py", line 97, in submit_build
    test_only=args.test_only, callback=upload_print_callback(args))
  File "/Users/rdebarros/work/anaconda-build/binstar_build_client/mixins/build.py", line 57, in submit_for_build
    s3res = requests.post(s3url, data=data_stream, verify=True, timeout=10 * 60 * 60, headers=headers)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(message_body)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/httplib.py", line 866, in send
    self.sock.sendall(datablock)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 220, in sendall
    sent = self._send_until_done(data[total_sent:total_sent+SSL_WRITE_BLOCKSIZE])
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 206, in _send_until_done
    return self.connection.send(data)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/site-packages/OpenSSL/SSL.py", line 950, in send
    self._raise_ssl_error(self._ssl, result)
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/site-packages/OpenSSL/SSL.py", line 871, in _raise_ssl_error
    _raise_current_error()
  File "/Users/rdebarros/miniconda3/envs/anaconda.org/lib/python2.7/site-packages/OpenSSL/_util.py", line 22, in exception_from_error_queue
    raise exceptionType(errors)
Error: [('SSL routines', 'ssl3_write_pending', 'bad write retry')]

**Comment by dsludwig** [comment]
Ok.. I think this is blocked on shazow/urllib3#717 then. As far as I can tell, this may be a while - a new version of urllib3 will need to be released, and then a new version of requests including the updated urllib3.

**Comment by rafaelhbarros** [comment]
try reproducing it, not sure if that was a fringe case or not.

**Comment by dsludwig** [comment]
I can reproduce this. Based on the linked bug, it would occur anytime the uploaded data is large enough.

Perhaps we should require `requests <= 2.7`?

**Comment by rafaelhbarros** [comment]
if that's the fix, I would suggest talking with more people.

**Comment by srossross** [comment]
:+1:

**Pull request merged**
