### PR TITLE
PR: Requests/PyOpenSSL version warning

### PR DESCRIPTION
**Pull request by dsludwig**
Removes restriction on requests version, generates a warning when a user tries to upload a package that triggers the bug.

I'm not sure if it should still show the whole traceback, since it's a known issue...  perhaps in case the OpenSSL error is not the one we are warning about?

Issue #256

### CODE REVIEW

**Comment by rafaelhbarros** [comment]
How do I test? How do I trigger the warning and how do I avoid the warning? What setup do I need to have locally?

**Comment by dsludwig** [comment]
To generate the warning, make sure you have installed:

* `requests > 2.7.0`
* `pyopenssl`, `pyasn1`, `ndg-httpsclient`

and try to upload a large package (10-100kB+).

To avoid the warning:

* downgrade requests to 2.7 OR
* uninstall pyopenssl

**Comment by rafaelhbarros** [comment]
will the build ever finish?

**Comment by dsludwig** [comment]
No (not until the Windows workers are fixed). It is waiting for the Windows worker builds - all the others have completed successfully.

**Pull request merged**
