### PR TITLE
fix remove syslog handler

### PR DESCRIPTION
**Pull request by srossross**
@rafaelhbarros

### CODE REVIEW

**Comment by srossross** [comment]
Fixes anaconda-server/anaconda-build#70 and Anaconda-Server/anaconda-client#126

**Comment by rafaelhbarros** [comment]
LGTM.

**Comment by malev** [comment]
:+1:

**Comment by srossross** [comment]
Yes, lets release!

**Comment by srossross** [comment]
The tests are passing for linux-64 and 32 I'm going to merge.

**Pull request merged**
