### PR TITLE
flipped the --no-register to --register and made it not be default

### PR DESCRIPTION
**Pull request by rafaelhbarros**
Related to #231

Title says it all.

### CODE REVIEW

**Comment by dsludwig** [comment]
LGTM

**Comment by rafaelhbarros** [comment]
I'm a bit worried about merging. Do you think I should?

**Comment by dsludwig** [comment]
Hmm.. should we save this for a major release? So that we are not issuing a breaking change on a minor release?

**Comment by rafaelhbarros** [comment]
makes sense.

**Comment by rafaelhbarros** [comment]
@srossross can you comment?

**Comment by srossross** [comment]
I think this is going to confuse existing users. 

Can the `auto_register` default be configurable from `anaconda config` eg: 
```
anaconda config --set auto_register yes
```

**Comment by rafaelhbarros** [comment]
Good idea on the config. Let me change that as soon as I can.

**Pull request closed without merging**
