### PR TITLE
Upload notebooks with thumbnails

### PR DESCRIPTION
**Pull request by malev**
Deprecate
`anaconda notebook upload`

Invite people to use:
`anaconda upload notebook.ipynb`

#295

### CODE REVIEW

**Comment by dsludwig** [comment]
For thumbnails, we need add something to update the package attributes if it's specified. I think it'd also be useful to have server UI for this, but that's a whole separate thing.

**Comment by malev** [comment]
@dsludwig I agree with you.
It would be great to be able to change package attributes when uploading a new distribution. But that should go into another issue. I talked with @stephenakearns a lot about being able to upload a package as private and being able to change the visibility of a package from the upload.

**Comment by malev** [comment]
@dsludwig #302 has been created.
Now, what concerts to this PR. what do you think?

**Comment by dsludwig** [comment]
:+1:

**Pull request merged**
