### PR TITLE
fix notebook usage spacing

### PR DESCRIPTION
**Pull request by electronwill**
fix notebook usage spacing

### CODE REVIEW

**Comment by electronwill** [comment]
http://docs.anaconda.org/cli.html#Notebook is showing all of this on a single line with no separation between commands, and this should fix that.

**Comment by malev** [comment]
mmh I don't like the way it looks on the help: `anaconda notebook --help`
I wonder if we can find a better solution

**Comment by electronwill** [comment]
Looks like this is populated in https://github.com/Anaconda-Server/docs.anaconda.org/blob/master/content/_cli/anaconda-client.html by this command:

json_command_line_method('notebook', 'anaconda notebook --json-help', 3)

Perhaps "anaconda notebook --help" could output the dense text version and "anaconda notebook --json-help" could output the version that will preserve line breaks when Hyde makes it into html.

**Comment by stephenakearns** [comment]
Hi @electronwill - I see this PR open for 23 days - is that something we can finish and close?

**Comment by electronwill** [comment]
http://docs.anaconda.org/cli.html#Notebook is still showing the incorrect formatting. @malev is there any good way to show line breaks on the site and also make it look good in ``anaconda notebook --help`` ?

**Comment by dsludwig** [comment]
@electronwill adding a newline after `Usage:` (while keeping the indent) should show the examples as a code block, with newlines preserved:

```
Usage:

    anaconda notebook upload
    anaconda notebook download ...
```

**Comment by electronwill** [comment]
OK, went ahead and made that change. Please merge if you think it's ready, and let me know when the changed version is released, and I'll rebuild the docs to include the fix.

**Comment by electronwill** [comment]
@dsludwig , how can I be sure to see when the change is released into production?

**Comment by dsludwig** [comment]
There will be an email sent out when the next version of Anaconda Cloud is released; the new version of anaconda-client will accompany it.

**Comment by electronwill** [comment]
Perfect. Thank you!

**Pull request merged**
